server:
  #服务端口
  port: 11002

spring:
  application:
    #服务名称
    name: app-order

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: eci_root
  jpa:
    show-sql: true

#Eureka配置
eureka:
  instance:
    #是否微服务调用地址为IP优先(缺省值false)
    prefer-ip-address: false

    #主机IP
    ip-address: 127.0.0.1

    #注册中心微服务名(默认为：机器主机名:应用名称:应用端口)
    instance-id: ${eureka.instance.ip-address}:${server.port}

    #客户端向服务器发送心跳的频率(缺省值30s)
    lease-renewal-interval-in-seconds: 30

  client:
    #是否将自己作为客户端注册到注册中心(缺省值true)
    register-with-eureka: true

    #是否从注册中心获取注册信息(缺省值true)
    fetch-registry: true

    #从注册中心获取注册信息的间隔时间(缺省值30s)
    #测试环境，可以适当提高Client端拉取Server注册信息的频率
    registry-fetch-interval-seconds: 30

    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
